# Generated by Django 3.1.12 on 2024-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
