# Generated by Django 3.1.12 on 2024-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicte_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
